### ISSUE TITLE
Problems Head for Bing Search

### ISSUE THREAD

**Issue by Leanwit** [clips/pattern#155]
Hi, i have a problem with pattern.web. Especifically with module search Engines Bing.
When i get the results, i have this problem:

> pattern.web.URLError: Invalid header value 'Basic OlZuSkVLNEhUbG50RTNTeUY1OFFMa1VDTHAvNzh0a1lqVjFGbDNKN2xIYTA9\n'

I copied exactly the examples, and stills this error.
Actually, i have Python 2.7.12. In my server, i have a Python 2.7.9 and works fine, and my other computer i have Python 2.7.6 and works too.

I checked all other libraries and the versions its same, minus Python.
It may be that the version of Python is generating problems ?

Thanks for all. Clips Pattern is amazing

**Comment by shawnanctil** [comment]
I'm having the same problem. Also running Python 2.7.12. Have not tried it on other versions.

**Comment by hubitor** [comment]
Same error with Anaconda 4.2.0

**Comment by ebeneeza** [comment]
Same on 2.7.11

**Comment by markus-beuckelmann** [comment]
I decided to open a new issue on this, since Bing is actually only one out of many APIs that currently do not work properly in Pattern due to authentication problems / API changes. Note that Bing Search API is a paid, subscription-based service now, so we'll have to refactor some of our code anyway.

Thank you for your reports, feel free to contribute to issue #181!
